### ISSUE TITLE
Matcher for Capybara nodes

### ISSUE THREAD

**Issue by ecbypi** [jmondo/orderly#1]
It would be useful to be able to do the following:

``` ruby
this = find('.this')
that = find('.that')

this.should appear_before that
```

There are a lot of cases where I'm already working with Capybara nodes in a spec and want to assert something about their order.  I tried using `Node#text`, but since the matcher uses `page.body` instead of `page.text`, this doesn't work.

I'd be happy to submit a pull request, but wanted to see if you thought this would be a feature worth pursuing.

**Comment by dkniffin** [comment]
I know this is an old issue, but I just stumbled upon it and it doesn't look like it's been resolved yet. I just made a PR.
