### ISSUE TITLE
Matching against `page.text`

### ISSUE THREAD

**Issue by ecbypi** [jmondo/orderly#2]
Sometimes I want to assert content that is built across DOM elements.  

``` html
<dl>
  <dt>First name: </dt>
  <dd>Rob</dt>

  <dt>Last name: </dt>
  <dd>64</dt>
</dl>
```

``` ruby
'First name: Rob'.should appear_before 'Last name: 64'
```

This would work if there was a matcher that used `page.text` or an option to use it in `appears_before`.  

Curious if you think this would be worth working on a pull request.

**Comment by IlkhamGaysin** [comment]
@jmondo actually I expect the text to be before some and as I see the gem uses under the hood `String#index` so as we match agains the text there might be some error when some data would be within html attrs or let's say I expect the text `ability` to be above `option` within my html document 

***GIVEN***

```html
 <select>
   <option>ability</option>
   <option>option</option>
 </select>
```

***TEST***

```ruby
  expect("ability").to appear_before("option")
```

That example would fail as `html.index("ability") < html.index("option") => false` 

***FIX****

To fix that we need compare against text not the html.

**Comment by fschwahn** [comment]
@IlkhamGaysin you are right, but we cannot just change it to text, because existing uses might rely on html being compared. If you submit a PR which makes this an option (for example by allowing `expect("ability").to appear_before("option", only_text: true)`) I'd be willing to merge it.

**Comment by IlkhamGaysin** [comment]
@fschwahn give me a chance

**Comment by IlkhamGaysin** [comment]
@fschwahn PR's done https://github.com/jmondo/orderly/pull/9
